Function of highlighting href links in post
Feykicat23/firstProject pull request #9
Opened 2023-08-21 20:13 UTC by Feykicat23

2023-08-24 20:31 UTC, burtovoy requested changes

2023-08-24 20:31 UTC, burtovoy commented on public/assets/validMail.js
> +  const popularEndsOfMail = [
Здесь словарь не нужен. Давай просто по шаблону проверять. Можно найти какую-нибудь популярную регулярку и сделать чтобы работало так же. Только без регулярки

2023-08-24 20:31 UTC, burtovoy commented on public/assets/validMail.js
> +  const otherEndsOfMail = ['.com', '.net', '.org', '.gov', '.edu', '.info', '.us', '.ru', '.app', '.store',
Тоже самое

2023-08-24 20:39 UTC, Feykicat23 commented on public/assets/validMail.js
> +  const popularEndsOfMail = [
> Здесь словарь не нужен. Давай просто по шаблону проверять. Можно найти какую-нибудь популярную регулярку и сделать чтобы работало так же. Только без регулярки

А объясни подробнее почему так? По какому шаблону?

2023-08-25 17:11 UTC, burtovoy commented on public/assets/validMail.js
> +  const popularEndsOfMail = [
Без словаря, да. Представь регулярку, и нужно тоже самое только без регулярки.

2023-08-28 11:03 UTC, burtovoy requested changes
А почему 2 функции из разных заданий в одном PR?

Плюс нужны тесты к каждой функции

2023-08-28 15:01 UTC, closed without merging